
version: '2.2'

services:

  starter_client:
    build:
      context: client
    user: nobody
    image: cyberdojo/starter-client
    init: true
    container_name: test-starter-client
    read_only: true
    tmpfs: /tmp
    depends_on:
      - starter
    restart: 'no'
    ports:
      - 4528:4528

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  starter:
    build:
      context: server
      args:
        - SHA
    user: nobody
    image: cyberdojo/starter
    init: true
    container_name: test-starter-server
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./server/start_points:/app/start_points:ro

